module Backend.ARMThumb.Scalar

import Backend.ARMThumb.IR
import Data.String

%default total

public export
to_float32_helper : NarrowFloatFormat -> String
to_float32_helper Binary16 = ".Lscalar_f16_to_f32"
to_float32_helper FP8E4M3 = ".Lscalar_e4m3_to_f32"
to_float32_helper FP8E5M2 = ".Lscalar_e5m2_to_f32"
to_float32_helper FP6E3M2 = ".Lscalar_e3m2_to_f32"
to_float32_helper OotomoE5M3 = ".Lscalar_e5m3_to_f32"

public export
from_float32_helper : NarrowFloatFormat -> String
from_float32_helper Binary16 = ".Lscalar_f32_to_f16"
from_float32_helper FP8E4M3 = ".Lscalar_f32_to_e4m3"
from_float32_helper FP8E5M2 = ".Lscalar_f32_to_e5m2"
from_float32_helper FP6E3M2 = ".Lscalar_f32_to_e3m2"
from_float32_helper OotomoE5M3 = ".Lscalar_f32_to_e5m3"

||| Descriptor bits consumed by the generic signed-small-float helpers:
|||   bits 0..3   trailing significand width
|||   bits 4..7   exponent width
|||   bits 8..15  exponent bias
|||   bits 16..17 conversion policy
||| Policy 0 = IEEE binary16, 1 = saturating E5M2,
||| 2 = saturating E4M3, 3 = saturating finite-only E3M2.
private
scalar_helper_lines : List String
scalar_helper_lines =
  [ ""
  , "@ Narrow scalar conversion helpers."
  , "@ All helpers take/return raw payload bits in r0."
  , "@ The generic signed formats use round-to-nearest, ties-to-even."
  , ""
  , ".Lscalar_f16_to_f32:"
  , "        movw    r1, #0x0f5a"
  , "        movt    r1, #0x0000"
  , "        b.w     .Lscalar_decode_generic"
  , ".Lscalar_e5m2_to_f32:"
  , "        movw    r1, #0x0f52"
  , "        movt    r1, #0x0001"
  , "        b.w     .Lscalar_decode_generic"
  , ".Lscalar_e4m3_to_f32:"
  , "        movw    r1, #0x0743"
  , "        movt    r1, #0x0002"
  , "        b.w     .Lscalar_decode_generic"
  , ".Lscalar_e3m2_to_f32:"
  , "        movw    r1, #0x0332"
  , "        movt    r1, #0x0003"
  , "        b.w     .Lscalar_decode_generic"
  , ""
  , ".Lscalar_f32_to_f16:"
  , "        movw    r1, #0x0f5a"
  , "        movt    r1, #0x0000"
  , "        b.w     .Lscalar_encode_generic"
  , ".Lscalar_f32_to_e5m2:"
  , "        movw    r1, #0x0f52"
  , "        movt    r1, #0x0001"
  , "        b.w     .Lscalar_encode_generic"
  , ".Lscalar_f32_to_e4m3:"
  , "        movw    r1, #0x0743"
  , "        movt    r1, #0x0002"
  , "        b.w     .Lscalar_encode_generic"
  , ".Lscalar_f32_to_e3m2:"
  , "        movw    r1, #0x0332"
  , "        movt    r1, #0x0003"
  , "        b.w     .Lscalar_encode_generic"
  , ""
  , "@ Ootomo-Naruse unsigned E5M3 storage conversion."
  , ".Lscalar_e5m3_to_f32:"
  , "        uxtb    r0, r0"
  , "        lsl.w   r0, r0, #20"
  , "        movw    r1, #0x0000"
  , "        movt    r1, #0x3808"
  , "        add.w   r0, r0, r1"
  , "        bx      lr"
  , ".Lscalar_f32_to_e5m3:"
  , "        movw    r1, #0x0000"
  , "        movt    r1, #0x3800"
  , "        sub.w   r0, r0, r1"
  , "        lsr.w   r0, r0, #20"
  , "        uxtb    r0, r0"
  , "        bx      lr"
  , ""
  , "@ Decode signed IEEE-like small float in r0 using descriptor r1."
  , ".Lscalar_decode_generic:"
  , "        push.w  {r4-r7, lr}"
  , "        and.w   r2, r1, #15"
  , "        ubfx    r3, r1, #4, #4"
  , "        ubfx    r4, r1, #8, #8"
  , "        ubfx    r5, r1, #16, #2"
  , "        add.w   r6, r2, r3"
  , "        lsr.w   r7, r0, r6"
  , "        and.w   r7, r7, #1"
  , "        lsl.w   r7, r7, #31"
  , "        movs    r6, #1"
  , "        lsl.w   r6, r6, r2"
  , "        subs    r6, r6, #1"
  , "        and.w   r1, r0, r6"
  , "        movs    r6, #1"
  , "        lsl.w   r6, r6, r3"
  , "        subs    r6, r6, #1"
  , "        lsr.w   r0, r0, r2"
  , "        and.w   r0, r0, r6"
  , "        movs    r3, #1"
  , "        lsl.w   r3, r3, r2"
  , "        subs    r3, r3, #1"
  , "        cmp     r5, #1"
  , "        bhi     .Lscalar_decode_check_e4"
  , "        cmp     r0, r6"
  , "        beq     .Lscalar_decode_ieee_special"
  , "        b       .Lscalar_decode_finite"
  , ".Lscalar_decode_check_e4:"
  , "        cmp     r5, #2"
  , "        bne     .Lscalar_decode_finite"
  , "        cmp     r0, r6"
  , "        bne     .Lscalar_decode_finite"
  , "        cmp     r1, r3"
  , "        beq     .Lscalar_decode_e4_nan"
  , ".Lscalar_decode_finite:"
  , "        cmp     r0, #0"
  , "        beq     .Lscalar_decode_zero_or_subnormal"
  , "        sub.w   r0, r0, r4"
  , "        add.w   r0, r0, #127"
  , "        lsl.w   r0, r0, #23"
  , "        rsb.w   r2, r2, #23"
  , "        lsl.w   r1, r1, r2"
  , "        orr.w   r0, r0, r1"
  , "        orr.w   r0, r0, r7"
  , "        pop.w   {r4-r7, pc}"
  , ".Lscalar_decode_zero_or_subnormal:"
  , "        cmp     r1, #0"
  , "        beq     .Lscalar_decode_zero"
  , "        rsb.w   r0, r4, #128"
  , "        adds    r3, r3, #1"
  , ".Lscalar_decode_subnormal_loop:"
  , "        tst.w   r1, r3"
  , "        bne     .Lscalar_decode_subnormal_ready"
  , "        lsl.w   r1, r1, #1"
  , "        subs    r0, r0, #1"
  , "        b       .Lscalar_decode_subnormal_loop"
  , ".Lscalar_decode_subnormal_ready:"
  , "        subs    r3, r3, #1"
  , "        and.w   r1, r1, r3"
  , "        lsl.w   r0, r0, #23"
  , "        rsb.w   r2, r2, #23"
  , "        lsl.w   r1, r1, r2"
  , "        orr.w   r0, r0, r1"
  , "        orr.w   r0, r0, r7"
  , "        pop.w   {r4-r7, pc}"
  , ".Lscalar_decode_zero:"
  , "        mov     r0, r7"
  , "        pop.w   {r4-r7, pc}"
  , ".Lscalar_decode_ieee_special:"
  , "        movw    r0, #0x0000"
  , "        movt    r0, #0x7f80"
  , "        cmp     r1, #0"
  , "        beq     .Lscalar_decode_special_finish"
  , "        rsb.w   r2, r2, #23"
  , "        lsl.w   r1, r1, r2"
  , "        orr.w   r0, r0, r1"
  , ".Lscalar_decode_special_finish:"
  , "        orr.w   r0, r0, r7"
  , "        pop.w   {r4-r7, pc}"
  , ".Lscalar_decode_e4_nan:"
  , "        movw    r0, #0x0000"
  , "        movt    r0, #0x7fc0"
  , "        orr.w   r0, r0, r7"
  , "        pop.w   {r4-r7, pc}"
  , ""
  , "@ Encode Float32 raw bits in r0 using descriptor r1."
  , ".Lscalar_encode_generic:"
  , "        push.w  {r4-r11, lr}"
  , "        and.w   r2, r1, #15"
  , "        ubfx    r3, r1, #4, #4"
  , "        ubfx    r4, r1, #8, #8"
  , "        ubfx    r5, r1, #16, #2"
  , "        add.w   r8, r2, r3"
  , "        lsr.w   r6, r0, #31"
  , "        lsl.w   r6, r6, r8"
  , "        ubfx    r7, r0, #23, #8"
  , "        ubfx    r0, r0, #0, #23"
  , "        mov.w   r8, #1"
  , "        lsl.w   r8, r8, r3"
  , "        sub.w   r8, r8, #1"
  , "        cmp     r7, #255"
  , "        beq     .Lscalar_encode_special"
  , "        cmp     r7, #0"
  , "        beq     .Lscalar_encode_zero"
  , "        sub.w   r7, r7, #127"
  , "        rsb.w   r1, r4, #1"
  , "        cmp     r7, r1"
  , "        blt     .Lscalar_encode_subnormal"
  , "        sub.w   r1, r8, r4"
  , "        cmp     r5, #1"
  , "        bhi     .Lscalar_encode_have_max"
  , "        subs    r1, r1, #1"
  , ".Lscalar_encode_have_max:"
  , "        cmp     r7, r1"
  , "        bgt     .Lscalar_encode_overflow"
  , "        rsb.w   r9, r2, #23"
  , "        lsr.w   r10, r0, r9"
  , "        mov.w   r11, #1"
  , "        lsl.w   r11, r11, r9"
  , "        sub.w   r11, r11, #1"
  , "        and.w   r11, r0, r11"
  , "        movs    r1, #1"
  , "        sub.w   r9, r9, #1"
  , "        lsl.w   r1, r1, r9"
  , "        add.w   r9, r9, #1"
  , "        cmp     r11, r1"
  , "        bhi     .Lscalar_encode_normal_increment"
  , "        bne     .Lscalar_encode_normal_rounded"
  , "        tst.w   r10, #1"
  , "        beq     .Lscalar_encode_normal_rounded"
  , ".Lscalar_encode_normal_increment:"
  , "        add.w   r10, r10, #1"
  , ".Lscalar_encode_normal_rounded:"
  , "        movs    r1, #1"
  , "        lsl.w   r1, r1, r2"
  , "        cmp     r10, r1"
  , "        bne     .Lscalar_encode_pack_normal"
  , "        mov.w   r10, #0"
  , "        adds    r7, r7, #1"
  , ".Lscalar_encode_pack_normal:"
  , "        add.w   r7, r7, r4"
  , "        cmp     r5, #1"
  , "        bhi     .Lscalar_encode_pack_unreserved"
  , "        cmp     r7, r8"
  , "        bhs     .Lscalar_encode_overflow"
  , "        b       .Lscalar_encode_pack_bits"
  , ".Lscalar_encode_pack_unreserved:"
  , "        cmp     r7, r8"
  , "        bhi     .Lscalar_encode_overflow"
  , "        cmp     r5, #2"
  , "        bne     .Lscalar_encode_pack_bits"
  , "        cmp     r7, r8"
  , "        bne     .Lscalar_encode_pack_bits"
  , "        movs    r1, #1"
  , "        lsl.w   r1, r1, r2"
  , "        subs    r1, r1, #1"
  , "        cmp     r10, r1"
  , "        beq     .Lscalar_encode_overflow"
  , ".Lscalar_encode_pack_bits:"
  , "        lsl.w   r7, r7, r2"
  , "        orr.w   r0, r6, r7"
  , "        orr.w   r0, r0, r10"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_subnormal:"
  , "        rsb.w   r1, r4, #0"
  , "        sub.w   r1, r1, r2"
  , "        cmp     r7, r1"
  , "        blt     .Lscalar_encode_zero"
  , "        movw    r1, #0x0000"
  , "        movt    r1, #0x0080"
  , "        orr.w   r0, r0, r1"
  , "        mov.w   r9, #24"
  , "        sub.w   r9, r9, r4"
  , "        sub.w   r9, r9, r7"
  , "        sub.w   r9, r9, r2"
  , "        lsr.w   r10, r0, r9"
  , "        mov.w   r11, #1"
  , "        lsl.w   r11, r11, r9"
  , "        sub.w   r11, r11, #1"
  , "        and.w   r11, r0, r11"
  , "        movs    r1, #1"
  , "        sub.w   r9, r9, #1"
  , "        lsl.w   r1, r1, r9"
  , "        cmp     r11, r1"
  , "        bhi     .Lscalar_encode_sub_increment"
  , "        bne     .Lscalar_encode_sub_rounded"
  , "        tst.w   r10, #1"
  , "        beq     .Lscalar_encode_sub_rounded"
  , ".Lscalar_encode_sub_increment:"
  , "        add.w   r10, r10, #1"
  , ".Lscalar_encode_sub_rounded:"
  , "        movs    r1, #1"
  , "        lsl.w   r1, r1, r2"
  , "        cmp     r10, r1"
  , "        bne     .Lscalar_encode_sub_pack"
  , "        orr.w   r0, r6, r1"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_sub_pack:"
  , "        orr.w   r0, r6, r10"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_special:"
  , "        cmp     r0, #0"
  , "        bne     .Lscalar_encode_nan"
  , "        cmp     r5, #0"
  , "        beq     .Lscalar_encode_infinity"
  , "        b       .Lscalar_encode_overflow"
  , ".Lscalar_encode_nan:"
  , "        cmp     r5, #3"
  , "        beq     .Lscalar_encode_nan_zero"
  , "        movs    r1, #1"
  , "        lsl.w   r1, r1, r2"
  , "        subs    r1, r1, #1"
  , "        cmp     r5, #2"
  , "        beq     .Lscalar_encode_nan_e4"
  , "        movs    r0, #1"
  , "        subs    r3, r2, #1"
  , "        lsl.w   r0, r0, r3"
  , "        lsl.w   r3, r8, r2"
  , "        orr.w   r0, r0, r3"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_nan_e4:"
  , "        lsl.w   r3, r8, r2"
  , "        orr.w   r0, r3, r1"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_nan_zero:"
  , "        movs    r0, #0"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_infinity:"
  , "        lsl.w   r0, r8, r2"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_overflow:"
  , "        movs    r1, #1"
  , "        lsl.w   r1, r1, r2"
  , "        subs    r1, r1, #1"
  , "        cmp     r5, #0"
  , "        beq     .Lscalar_encode_infinity"
  , "        cmp     r5, #1"
  , "        beq     .Lscalar_encode_overflow_e5m2"
  , "        cmp     r5, #2"
  , "        beq     .Lscalar_encode_overflow_e4m3"
  , "        lsl.w   r0, r8, r2"
  , "        orr.w   r0, r0, r1"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_overflow_e5m2:"
  , "        subs    r3, r8, #1"
  , "        lsl.w   r0, r3, r2"
  , "        orr.w   r0, r0, r1"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_overflow_e4m3:"
  , "        lsl.w   r0, r8, r2"
  , "        subs    r1, r1, #1"
  , "        orr.w   r0, r0, r1"
  , "        orr.w   r0, r0, r6"
  , "        pop.w   {r4-r11, pc}"
  , ".Lscalar_encode_zero:"
  , "        mov     r0, r6"
  , "        pop.w   {r4-r11, pc}"
  ]

public export
scalar_helpers : String
scalar_helpers = unlines scalar_helper_lines
